### ISSUE TITLE
figure not shown

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/tutorials#41]
https://github.com/deepmodeling/tutorials/blob/9706dca38e132d995925b7b6fe152105c7fbdb8e/source/Tutorials/DeePMD-kit/learnDoc/Theory.md?plain=1#L22

This figure (https://gitee.com/liangwenshuo1118/myblog/blob/master/img/descriptor.png) is not available.

**Comment by likefallwind** [comment]
@LiangWenshuo1118 please fix this issue
