### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/tutorials#57]
The following files look duplicated:
- https://github.com/deepmodeling/tutorials/blob/7a11d3db493010e78a8d3c674700bc7a6815c7ca/source/Tutorials/DeePMD-kit/learnDoc/DeePMD-kit(v2.0.3).md
- https://github.com/deepmodeling/tutorials/blob/7a11d3db493010e78a8d3c674700bc7a6815c7ca/source/Tutorials/DeePMD-kit/learnDoc/Handson-Tutorial(v2.0.3).md

The following files are duplicated as well:
- https://github.com/deepmodeling/tutorials/blob/7a11d3db493010e78a8d3c674700bc7a6815c7ca/source/CaseStudies/Examples/methane.md
- https://github.com/deepmodeling/tutorials/blob/7a11d3db493010e78a8d3c674700bc7a6815c7ca/source/CaseStudies/Gas-phase/methane.md

@likefallwind Could you take a look?

**Comment by likefallwind** [comment]
@LiangWenshuo1118 would you please have a look?
